### PR TITLE
Add note about  maven and java dependency

### PR DESCRIPTION
**Pull request by vanatteveldt**

### CODE REVIEW

**Comment by karussell** [comment]
> It seems that it doesn't work with openjdk

which one does not work with openjdk?

**Comment by vanatteveldt** [comment]
I tried to install on my home computer, which was running openjdk-7, and maven complained about not finding the java compiler. Removing openjdk and installing sun fixed the problem, so I assumed that openjdk was the problem, but maybe there was some weird path issue. Feel free to remove the note if it does work with openjdk, of course.

**Comment by karussell** [comment]
should work with openjdk, yes

**Comment by vanatteveldt** [comment]
OK, removed the openjdk remark, now it's just the maven dependency.

BTW there are two questions I had about using it:

1) if you have a cluster with multiples nodes, do you need to install reindex on all nodes or just on the one you're calling? It seems like the latter works
2) What does the -d ' { "term" : { "count" : 2 } }' do? Is that limiting the amount of documents to reindex? It seems to work fine without the body.

It might be good to add a note in de readme, if you can confirm these points I'll happily add it to the pull request.

**Comment by karussell** [comment]
> you need to install reindex on all nodes

yes, thats necessary

Re the 'term', yes that is just the example for a filter

**Comment by vanatteveldt** [comment]
> yes, thats necessary

Are you sure? I've just copied a 100M document index to a different index (with more shards) on the same cluster, and I only installed reindex on the 'coordinator' node, and it seems to work fine?

**Comment by karussell** [comment]
But who is the 'coordinator'? That can change if it goes down etc

**Comment by vanatteveldt** [comment]
In the concrete case, the coordinator is a node without data that is used as the access points for most of the queries (to take some load off the data nodes and to make it easier to shutdown single data nodes without worrying that a client might use that as its access point).

I used it as a one-off operation to change the # of shards, so downtime was no problem, but I suppose the fact that it worked means that reindex needs to be installed on only the node to which the request is made, or am I misinterpreting here? Anyway, if it is better to just install on all nodes, I guess it's not a good idea to make a comment in the readme. I'll add a comment on the filtering.

**Comment by karussell** [comment]
> Anyway, if it is better to just install on all nodes,
> I guess it's not a good idea to make a comment in the readme. 

Yes

> I'll add a comment on the filtering.

okay

**Pull request merged**
