### PR TITLE
Fixing build / install script

### PR DESCRIPTION
**Pull request by synhershko**
The plugin script is unusable with this plugin, and the provided build / installation script is broken.

I'd prefer to have the plugin installation script working, but as long as it won't - this will make the installation work

/cc @karussell

### CODE REVIEW

**Comment by karussell** [comment]
What is the problem when you try to install it? (I'm currently not using this in production so I'm happy for every contribution.)

**Comment by synhershko** [comment]
It doesn't find (so doesn't produce) the zip file

**Comment by karussell** [comment]
But it produces the zip file and also finds it. Sorry, don't understand what you mean:

``` bash
$ mvn -DskipTests clean package
$ FILE=`ls ./target/elasticsearch-*zip`
$ echo $FILE
# => ./target/elasticsearch-reindex-1.4.1.zip
```

**Comment by synhershko** [comment]
It didn't on my end when running reinstall.sh, and it was faster for me to fix it this way

**Comment by karussell** [comment]
If you execute the mvn command on its own do you get the zip file? Are you on linux/OSX?

**Pull request closed without merging**
