### PR TITLE
Fix addAlias arguments order

### PR DESCRIPTION
**Pull request by kalekseev**

### CODE REVIEW

**Comment by karussell** [comment]
What is the problem? Do you have a failing test before this change?

**Comment by kalekseev** [comment]
Sorry for the lack of the description I thought problem is obvious, but basically problem is that at this commit https://github.com/elasticsearch/elasticsearch/commit/411739fe3b5b2410fa9594edf27087718162225f agruments where swapped

[addAlias 1.4.0 javadoc](http://javadoc.kyubu.de/elasticsearch/v1.4.0/org/elasticsearch/action/admin/indices/alias/IndicesAliasesRequest.html#addAlias(java.lang.String,%20java.lang.String...))

**Comment by karussell** [comment]
Oh, ugly. And did some of our tests fail or did you run into this in production?

**Comment by kalekseev** [comment]
No tests pass without problem (before and after my change). I've founded it doing code review before using your plugin in my project.

**Comment by karussell** [comment]
> No tests pass without problem

Hmmh, that is kind of strange. Would you mind to add a small test showing the problem?

Strange that they did a change like this. Also AliasActions has now a different, inconsistent order ala indices, alias

**Comment by kalekseev** [comment]
Maybe later today i'll have time for small test



—
Отправлено из Mailbox

**Comment by kalekseev** [comment]
I've added test which cover copy aliases function

**Comment by karussell** [comment]
Thanks a lot!

**Pull request merged**
